name: PHP-HelloWorld

on:
  push:
    branches: [ mst ]
  pull_request:
    branches: [ mst ]

jobs:
  job1-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PW: ${{ secrets.DOCKER_PW}}
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PW
         
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      id: docker_build
      with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USER}}/php_helloworld

    - name: Verify
      run: echo ${{ steps.docker_build.outputs.digest }}
